server:
   port: 9191
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud
    password: root
    username: root
  application:
    name: user-service
mybatis:
  type-aliases-package: com.itheima.pojo
logging:
  level:
    com.itheima: debug
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    # 更倾向使用ip地址，而不是host名
    prefer-ip-address: true
    # ip地址
    ip-address: 127.0.0.1
